"""Internal marketing-lead email notifications via environment configuration only."""
from __future__ import annotations

import logging
import os
import smtplib
import ssl
from email.message import EmailMessage
from typing import Any

logger = logging.getLogger("amicor.marketing.notify")


def marketing_email_configured() -> bool:
    host = (os.getenv("MARKETING_SMTP_HOST") or "").strip()
    notify_to = (os.getenv("MARKETING_LEAD_NOTIFY_TO") or "").strip()
    mail_from = (os.getenv("MARKETING_SMTP_FROM") or "").strip()
    return bool(host and notify_to and mail_from)


def _safe_label(value: object, limit: int = 200) -> str:
    text = " ".join(str(value or "").split())
    return text[:limit]


def build_lead_notification(lead: Any) -> tuple[str, str]:
    lead_type = _safe_label(getattr(lead, "lead_type", ""), 64)
    subject = f"[Amicor Lead] {lead_type} — {_safe_label(getattr(lead, 'contact_name', ''), 80)}"
    lines = [
        "A new website lead was submitted.",
        "",
        f"Lead ID: {_safe_label(getattr(lead, 'id', ''), 64)}",
        f"Status: {_safe_label(getattr(lead, 'status', 'new'), 32)}",
        f"Inquiry type: {lead_type}",
        f"Subject: {_safe_label(getattr(lead, 'subject', ''), 80)}",
        f"Name: {_safe_label(getattr(lead, 'contact_name', ''), 128)}",
        f"Organization: {_safe_label(getattr(lead, 'organization_name', ''), 200)}",
        f"Email: {_safe_label(getattr(lead, 'work_email', ''), 200)}",
        f"Phone: {_safe_label(getattr(lead, 'phone', ''), 64)}",
        f"Service area: {_safe_label(getattr(lead, 'service_area', ''), 200)}",
        f"Organization type: {_safe_label(getattr(lead, 'organization_type', ''), 64)}",
        f"Preferred contact: {_safe_label(getattr(lead, 'preferred_contact_method', ''), 32)}",
        f"Lead source: {_safe_label(getattr(lead, 'lead_source', '') or getattr(lead, 'source_path', ''), 200)}",
        f"Consent: {bool(getattr(lead, 'consent', False))}",
        f"Submitted at: {_safe_label(getattr(lead, 'created_at', ''), 64)}",
        "",
        "Message / transportation needs:",
        _safe_label(
            getattr(lead, "message", None) or getattr(lead, "transportation_needs", None),
            2000,
        ),
        "",
        "This message was generated by the Amicor marketing lead API.",
    ]
    return subject, "\n".join(lines)


def send_lead_notification(lead: Any) -> dict[str, Any]:
    """
    Attempt SMTP notification using env vars only.

    Returns a result dict. Never raises to the caller for delivery failures.
    """
    if not marketing_email_configured():
        logger.info(
            "marketing_lead_email_skipped reason=not_configured lead_id=%s",
            getattr(lead, "id", None),
        )
        return {"attempted": False, "sent": False, "reason": "not_configured"}

    host = (os.getenv("MARKETING_SMTP_HOST") or "").strip()
    port_raw = (os.getenv("MARKETING_SMTP_PORT") or "587").strip()
    user = (os.getenv("MARKETING_SMTP_USER") or "").strip()
    password = os.getenv("MARKETING_SMTP_PASSWORD") or ""
    mail_from = (os.getenv("MARKETING_SMTP_FROM") or "").strip()
    notify_to = (os.getenv("MARKETING_LEAD_NOTIFY_TO") or "").strip()
    use_tls = (os.getenv("MARKETING_SMTP_USE_TLS") or "1").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }

    try:
        port = int(port_raw)
    except ValueError:
        logger.warning("marketing_lead_email_failed reason=invalid_port lead_id=%s", getattr(lead, "id", None))
        return {"attempted": True, "sent": False, "reason": "invalid_port"}

    subject, body = build_lead_notification(lead)
    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = mail_from
    message["To"] = notify_to
    message.set_content(body)

    try:
        if use_tls:
            context = ssl.create_default_context()
            with smtplib.SMTP(host, port, timeout=20) as smtp:
                smtp.ehlo()
                smtp.starttls(context=context)
                smtp.ehlo()
                if user:
                    smtp.login(user, password)
                smtp.send_message(message)
        else:
            with smtplib.SMTP(host, port, timeout=20) as smtp:
                if user:
                    smtp.login(user, password)
                smtp.send_message(message)
        logger.info(
            "marketing_lead_email_sent lead_id=%s lead_type=%s",
            getattr(lead, "id", None),
            getattr(lead, "lead_type", None),
        )
        return {"attempted": True, "sent": True, "reason": "sent"}
    except Exception as exc:
        # Do not log credentials, passwords, full message bodies, or recipient lists with secrets.
        logger.warning(
            "marketing_lead_email_failed reason=%s lead_id=%s exc_type=%s",
            "smtp_error",
            getattr(lead, "id", None),
            type(exc).__name__,
        )
        return {"attempted": True, "sent": False, "reason": "smtp_error"}
