"""Simulated opportunities for tests and local development. Not production records."""
from __future__ import annotations

from typing import Any


def simulated_opportunities() -> list[dict[str, Any]]:
    return [
        {
            "fixture_id": "sim-admin-remote",
            "company_name": "Example Operations Co",
            "opportunity_title": "Remote administrative support contractor",
            "description": (
                "Prepare email drafts, organize CRM notes, summarize reports, and draft follow-up "
                "messages. Fully remote. No license required."
            ),
            "location": "Remote",
            "remote_status": "remote",
            "engagement_type": "contract",
            "compensation_type": "hourly",
            "compensation_amount": 40.0,
            "compensation_period": "hour",
            "currency": "USD",
            "requirements": "Email writing, CRM organization, reporting summaries.",
            "skills_required": ["email", "crm", "reporting", "administrative"],
            "credentials_required": [],
            "physical_presence_required": "false",
            "source_url": "https://example.invalid/jobs/admin-support",
        },
        {
            "fixture_id": "sim-warehouse",
            "company_name": "Example Warehouse LLC",
            "opportunity_title": "Warehouse associate",
            "description": "On-site warehouse associate. Forklift and heavy lifting required every shift.",
            "location": "Minneapolis, MN",
            "remote_status": "on-site",
            "engagement_type": "w2",
            "compensation_type": "hourly",
            "compensation_amount": 18.0,
            "compensation_period": "hour",
            "currency": "USD",
            "requirements": "On-site presence, forklift, heavy lifting.",
            "skills_required": ["forklift"],
            "credentials_required": [],
            "physical_presence_required": "true",
            "source_url": "https://example.invalid/jobs/warehouse",
        },
        {
            "fixture_id": "sim-rn",
            "company_name": "Example Clinic",
            "opportunity_title": "Registered Nurse",
            "description": "Licensed RN to provide clinical judgment and in-person patient care. Nursing license required.",
            "location": "St. Paul, MN",
            "remote_status": "on-site",
            "engagement_type": "w2",
            "compensation_type": "salary",
            "compensation_amount": 80000.0,
            "compensation_period": "year",
            "currency": "USD",
            "requirements": "Active RN license and clinical judgment.",
            "skills_required": ["nursing"],
            "credentials_required": ["RN license"],
            "physical_presence_required": "true",
            "source_url": "https://example.invalid/jobs/rn",
        },
        {
            "fixture_id": "sim-missing",
            "company_name": "Unknown Company",
            "opportunity_title": "Role not described",
            "description": "",
            "location": None,
            "remote_status": None,
            "engagement_type": None,
            "compensation_type": None,
            "compensation_amount": None,
            "compensation_period": None,
            "currency": None,
            "requirements": "",
            "skills_required": [],
            "credentials_required": [],
            "physical_presence_required": "unknown",
            "source_url": None,
        },
        {
            "fixture_id": "sim-driver",
            "company_name": "Example Logistics",
            "opportunity_title": "Delivery driver",
            "description": "CDL not required. Valid driver's license and driving required to operate a vehicle daily.",
            "location": "Twin Cities",
            "remote_status": "on-site",
            "engagement_type": "contract",
            "compensation_type": "hourly",
            "compensation_amount": 22.0,
            "compensation_period": "hour",
            "currency": "USD",
            "requirements": "Driving required. Valid driver's license.",
            "skills_required": ["driving"],
            "credentials_required": ["driver's license"],
            "physical_presence_required": "true",
            "source_url": "https://example.invalid/jobs/driver",
        },
    ]
