"""Phase 2 internal lifecycle. Aliases preserve Phase 1 stored values. No live execution."""
from __future__ import annotations

LIFECYCLE_STAGES = (
    "DISCOVER",
    "QUALIFY",
    "PREPARE",
    "OWNER_REVIEW",
    "APPROVE",
    "MANUAL_EXTERNAL_HANDOFF",
    "ENGAGEMENT",
    "WORK_EXECUTION",
    "DELIVERABLE",
    "INVOICE_SUPPORT",
    "PAYMENT_STATUS",
    "REVENUE_RECONCILIATION",
    "ARCHIVE",
)

QUALIFICATION_DECISIONS = (
    "NOVA_CAN_PERFORM",
    "NOVA_CAN_PREPARE",
    "OWNER_ACTION_REQUIRED",
    "INSUFFICIENT_INFORMATION",
    "NOT_SUITABLE",
    "NOT_SUPPORTED",
    "PROHIBITED",
)

FACT_STATUSES = (
    "KNOWN_VERIFIED_FACT",
    "OWNER_PROVIDED_FACT",
    "MISSING_FACT",
    "UNVERIFIED_FACT",
    "NOT_APPLICABLE",
)

OPPORTUNITY_PRIORITIES = ("low", "normal", "high", "urgent")

DELIVERABLE_TYPES = (
    "REPORT",
    "DOCUMENT",
    "ANALYSIS",
    "PROPOSAL",
    "DATA_FILE",
    "PRESENTATION",
    "FOLLOW_UP_PACKAGE",
    "OTHER",
)

DELIVERABLE_STATUSES = (
    "DRAFT",
    "READY_FOR_REVIEW",
    "OWNER_APPROVED",
    "CONFIRMED_DELIVERED",
    "CANCELLED",
)

REVENUE_STAGES = (
    "ESTIMATED",
    "QUOTED",
    "CONTRACTED",
    "INVOICE_DRAFT",
    "INVOICED_EXTERNALLY",
    "PAYMENT_PENDING",
    "PARTIALLY_PAID",
    "PAID",
    "OVERDUE",
    "WRITTEN_OFF",
    "CANCELLED",
)

PAID_STAGES = {"PAID", "PARTIALLY_PAID"}

TASK_STATUS_ALIASES = {
    "TODO": "NOT_STARTED",
    "WAITING": "OWNER_REVIEW",
    "DONE": "COMPLETE",
}

ENGAGEMENT_STATUS_ALIASES = {
    "PLANNED": "NOT_STARTED",
    "NEW": "NEW",
    "WAITING_ON_OWNER": "OWNER_ACTION_REQUIRED",
}

APPROVAL_STATUS_ALIASES = {
    "CHANGES_REQUESTED": "NEEDS_CHANGES",
    "READY_FOR_REVIEW": "READY_FOR_OWNER_REVIEW",
    "APPROVED_FOR_FUTURE_SUBMISSION": "APPROVED",
}

OWNER_ACTION_CATEGORIES = (
    "REVIEW_DRAFT",
    "PROVIDE_INFORMATION",
    "PROVIDE_MISSING_INFORMATION",
    "UPLOAD_DOCUMENT",
    "VERIFY_REQUIREMENT",
    "VERIFY_BUSINESS_FACT",
    "MANUAL_SUBMISSION",
    "APPROVE_MANUAL_SUBMISSION",
    "SIGNATURE_REQUIRED",
    "LOGIN_REQUIRED",
    "CAPTCHA_REQUIRED",
    "INTERVIEW_REQUIRED",
    "PAYMENT_REQUIRED",
    "LEGAL_REVIEW_REQUIRED",
    "CONFIRM_DELIVERABLE",
    "CONFIRM_CONTRACT",
    "CONFIRM_PAYMENT_RECEIVED",
    "REVIEW_WEEKLY_REPORT",
    "RESOLVE_BLOCKER",
)

ACTION_TYPE_TO_CATEGORY = {
    "CAPTCHA": "CAPTCHA_REQUIRED",
    "IDENTITY_VERIFICATION": "VERIFY_REQUIREMENT",
    "LIVE_INTERVIEW": "INTERVIEW_REQUIRED",
    "PHONE_CALL": "INTERVIEW_REQUIRED",
    "LIVE_MEETING": "INTERVIEW_REQUIRED",
    "LEGAL_SIGNATURE": "SIGNATURE_REQUIRED",
    "CONTRACT_ACCEPTANCE": "LEGAL_REVIEW_REQUIRED",
    "BANK_INFORMATION": "PAYMENT_REQUIRED",
    "PAYOUT_SETUP": "PAYMENT_REQUIRED",
    "TAX_INFORMATION": "PROVIDE_INFORMATION",
    "SSN": "PROVIDE_INFORMATION",
    "BACKGROUND_CHECK": "VERIFY_REQUIREMENT",
    "LICENSE_VERIFICATION": "VERIFY_REQUIREMENT",
    "PRICING_COMMITMENT": "REVIEW_DRAFT",
    "FINANCIAL_COMMITMENT": "PAYMENT_REQUIRED",
    "LEGAL_CERTIFICATION": "LEGAL_REVIEW_REQUIRED",
    "ACCOUNT_CREATION": "LOGIN_REQUIRED",
    "PLATFORM_REQUIRES_HUMAN": "LOGIN_REQUIRED",
    "VERIFY_BUSINESS_FACT": "VERIFY_BUSINESS_FACT",
    "REVIEW_DRAFT": "REVIEW_DRAFT",
    "PROVIDE_MISSING_INFORMATION": "PROVIDE_MISSING_INFORMATION",
    "APPROVE_MANUAL_SUBMISSION": "APPROVE_MANUAL_SUBMISSION",
    "CONFIRM_DELIVERABLE": "CONFIRM_DELIVERABLE",
    "CONFIRM_CONTRACT": "CONFIRM_CONTRACT",
    "CONFIRM_PAYMENT_RECEIVED": "CONFIRM_PAYMENT_RECEIVED",
    "REVIEW_WEEKLY_REPORT": "REVIEW_WEEKLY_REPORT",
    "RESOLVE_BLOCKER": "RESOLVE_BLOCKER",
}

QUEUE_STATUSES = (
    "NEW",
    "READY",
    "ACTIVE",
    "BLOCKED",
    "OWNER_ACTION_REQUIRED",
    "COMPLETE",
    "ARCHIVED",
)

QUEUE_STATUS_MAP = {
    "NOT_STARTED": "NEW",
    "NEW": "NEW",
    "READY": "READY",
    "ACTIVE": "ACTIVE",
    "DELIVERABLE_READY": "ACTIVE",
    "WAITING_ON_CLIENT": "ACTIVE",
    "WAITING_ON_OWNER": "OWNER_ACTION_REQUIRED",
    "OWNER_ACTION_REQUIRED": "OWNER_ACTION_REQUIRED",
    "BLOCKED": "BLOCKED",
    "PAUSED": "BLOCKED",
    "COMPLETE": "COMPLETE",
    "CANCELLED": "ARCHIVED",
    "ARCHIVED": "ARCHIVED",
}

ENGAGEMENT_TRANSITIONS: dict[str, set[str]] = {
    "NOT_STARTED": {"NEW", "READY", "ACTIVE", "BLOCKED", "OWNER_ACTION_REQUIRED", "ARCHIVED", "CANCELLED"},
    "NEW": {"READY", "ACTIVE", "BLOCKED", "OWNER_ACTION_REQUIRED", "ARCHIVED", "CANCELLED"},
    "READY": {"ACTIVE", "BLOCKED", "OWNER_ACTION_REQUIRED", "ARCHIVED", "CANCELLED"},
    "ACTIVE": {"BLOCKED", "OWNER_ACTION_REQUIRED", "COMPLETE", "ARCHIVED", "PAUSED"},
    "WAITING_ON_OWNER": {"READY", "ACTIVE", "BLOCKED", "OWNER_ACTION_REQUIRED", "ARCHIVED"},
    "OWNER_ACTION_REQUIRED": {"READY", "ACTIVE", "BLOCKED", "ARCHIVED"},
    "WAITING_ON_CLIENT": {"ACTIVE", "BLOCKED", "OWNER_ACTION_REQUIRED", "COMPLETE", "ARCHIVED"},
    "DELIVERABLE_READY": {"ACTIVE", "COMPLETE", "OWNER_ACTION_REQUIRED", "ARCHIVED"},
    "BLOCKED": {"READY", "ACTIVE", "OWNER_ACTION_REQUIRED", "ARCHIVED", "CANCELLED"},
    "PAUSED": {"READY", "ACTIVE", "ARCHIVED"},
    "COMPLETE": {"ARCHIVED"},
    "CANCELLED": {"ARCHIVED"},
    "ARCHIVED": set(),
}

REVENUE_STAGE_ALIASES = {
    "INVOICED": "INVOICED_EXTERNALLY",
    "MANUAL_RECORD_ONLY": "INVOICED_EXTERNALLY",
    "OWNER_CONFIRMED_RECEIVED": "PAID",
    "RECEIVED": "PAID",
}

REPORT_STATUSES = (
    "DRAFT",
    "READY_FOR_OWNER_REVIEW",
    "APPROVED_FOR_MANUAL_USE",
    "ARCHIVED",
)

INVOICE_SUPPORT_STATUSES = (
    "DRAFT",
    "READY_FOR_OWNER_REVIEW",
    "APPROVED",
    "ARCHIVED",
)

RECURRING_SERIES_STATUSES = ("ACTIVE", "PAUSED", "ARCHIVED")
OCCURRENCE_STATUSES = ("OPEN", "COMPLETE", "SKIPPED")
FACT_VALUE_STATUSES = ("MISSING", "PROVIDED", "OWNER_PROVIDED", "VERIFIED", "EXPIRED", "NOT_APPLICABLE")
DISCLOSURE_STATUSES = ("DRAFT", "MANUAL_REVIEW_REQUIRED", "ACKNOWLEDGED", "ARCHIVED")

ANALYTICS_PERIODS = ("today", "week", "month", "all")

LIST_DEFAULT_LIMIT = 100
LIST_MAX_LIMIT = 200


def clamp_list_limit(limit: int | None, *, default: int = LIST_DEFAULT_LIMIT) -> int:
    value = default if limit is None else int(limit)
    if value < 1:
        return 1
    return min(value, LIST_MAX_LIMIT)


def normalize_task_status(value: str | None) -> str:
    token = str(value or "NOT_STARTED").strip().upper()
    return TASK_STATUS_ALIASES.get(token, token if token else "NOT_STARTED")


def normalize_engagement_status(value: str | None) -> str:
    token = str(value or "NOT_STARTED").strip().upper()
    return ENGAGEMENT_STATUS_ALIASES.get(token, token if token else "NOT_STARTED")


def queue_status_for(value: str | None) -> str:
    token = normalize_engagement_status(value)
    return QUEUE_STATUS_MAP.get(token, "NEW")


def normalize_revenue_stage(value: str | None) -> str:
    token = str(value or "ESTIMATED").strip().upper()
    return REVENUE_STAGE_ALIASES.get(token, token)


def normalize_approval_state(value: str | None) -> str:
    token = str(value or "DRAFT").strip().upper()
    return APPROVAL_STATUS_ALIASES.get(token, token)


def category_for_action(action_type: str) -> str:
    return ACTION_TYPE_TO_CATEGORY.get(action_type, "PROVIDE_INFORMATION")
